# Generated by Django 4.2.2 on 2023-10-15 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exoneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_Exoneration', models.CharField(max_length=200)),
                ('Description', models.TextField(max_length=600)),
            ],
            options={
                'verbose_name': 'Exoneration',
                'verbose_name_plural': 'Exonerations',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genre', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=600)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marque', models.CharField(max_length=50)),
                ('Nom', models.CharField(max_length=100)),
                ('Annee', models.DateField(auto_now=True)),
                ('Couleur', models.CharField(max_length=50)),
                ('Source_energie', models.CharField(max_length=50)),
                ('Num_chassis', models.CharField(max_length=50)),
                ('Num_moteur', models.CharField(max_length=50)),
                ('Date_circulation', models.DateTimeField()),
                ('Date_identification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moto',
                'verbose_name_plural': 'Motos',
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_pays', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Proprietaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('Mail', models.EmailField(max_length=100)),
                ('Tel', models.CharField(max_length=15)),
                ('Photo', models.ImageField(blank=True, upload_to='photoapp')),
            ],
            options={
                'verbose_name': 'Propriètaire',
                'verbose_name_plural': 'Propriètaires',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Utilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_utilisation', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=600)),
            ],
            options={
                'verbose_name': 'Utilisation',
                'verbose_name_plural': 'Utilisations',
            },
        ),
        migrations.CreateModel(
            name='Vente_Plaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_Plaque', models.CharField(max_length=50, unique=True)),
                ('Photo_proprietaire', models.ImageField(blank=True, upload_to='photoapp')),
                ('dates', models.DateField(auto_now=True)),
                ('Exonerations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PLAQUES_APP.exoneration')),
                ('Proprietaire', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PLAQUES_APP.proprietaires')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PLAQUES_APP.moto', unique=True)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
            },
        ),
        migrations.AddField(
            model_name='moto',
            name='Pays_fabrication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PLAQUES_APP.pays'),
        ),
        migrations.AddField(
            model_name='moto',
            name='Type_utilisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PLAQUES_APP.utilisation'),
        ),
        migrations.AddField(
            model_name='moto',
            name='genre_moto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PLAQUES_APP.genre'),
        ),
        migrations.AddField(
            model_name='moto',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PLAQUES_APP.proprietaires'),
        ),
    ]
