# Generated by Django 4.2.2 on 2023-10-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PLAQUES_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vente_Plaque',
            new_name='Enregistrement',
        ),
    ]
