# Generated by Django 4.2.2 on 2023-10-18 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PLAQUES_APP', '0002_rename_vente_plaque_enregistrement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_Plaque', models.CharField(max_length=50, unique=True)),
                ('Photo_proprietaire', models.ImageField(blank=True, upload_to='photoapp')),
                ('dates', models.DateField(auto_now=True)),
                ('Exonerations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PLAQUES_APP.exoneration')),
                ('Proprietaire', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PLAQUES_APP.proprietaires')),
            ],
            options={
                'verbose_name': 'Controle',
                'verbose_name_plural': 'Controle',
            },
        ),
    ]
