# Generated by Django 4.2.2 on 2023-10-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PLAQUES_APP', '0003_controle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Controle',
        ),
    ]
