# Generated by Django 4.2.2 on 2023-10-18 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PLAQUES_APP', '0005_controle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='moto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PLAQUES_APP.moto', unique=True),
        ),
    ]
