# Generated by Django 4.2.2 on 2023-10-18 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PLAQUES_APP', '0006_alter_controle_moto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='enregistrement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PLAQUES_APP.enregistrement'),
        ),
    ]
