# Generated by Django 4.2.2 on 2023-10-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PLAQUES_APP', '0007_alter_controle_enregistrement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controle',
            name='enregistrement',
        ),
    ]
