# Generated by Django 4.2.2 on 2023-10-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PLAQUES_APP', '0008_remove_controle_enregistrement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Controle',
        ),
    ]
