# Generated by Django 4.2.2 on 2023-10-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLAQUES_APP', '0010_controle'),
    ]

    operations = [
        migrations.AddField(
            model_name='controle',
            name='Dates',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
