# Generated by Django 4.2.2 on 2023-10-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLAQUES_APP', '0012_alter_controle_enregistrement_alter_controle_moto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='Proprietaire',
            field=models.TextField(max_length=100),
        ),
    ]
