# Generated by Django 4.2.2 on 2023-10-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PLAQUES_APP', '0017_rename_enregistrement_controle_num_plaque_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Controle',
        ),
    ]
