# Generated by Django 4.2.2 on 2023-10-20 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PLAQUES_APP', '0018_delete_controle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_Plaque', models.CharField(max_length=100)),
                ('Dates', models.DateTimeField(auto_now=True)),
                ('Exonerations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PLAQUES_APP.exoneration')),
                ('Proprietaires', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PLAQUES_APP.proprietaires')),
            ],
            options={
                'verbose_name': 'Controle',
                'verbose_name_plural': 'Controle',
            },
        ),
    ]
