# Generated by Django 4.2.2 on 2023-10-20 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PLAQUES_APP', '0019_controle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Controle',
        ),
    ]
